CREATE TABLE IF NOT EXISTS mpa
(
    id int generated by default as identity primary key,
    mpa varchar(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres
(
    id int generated by default as identity primary key,
    name varchar(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films
(
    id int generated by default as identity primary key,
    name varchar(60) NOT NULL,
    description varchar(250),
    release_date date NOT NULL,
    duration int NOT NULL,
    mpa_id int NOT NULL REFERENCES mpa (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id int REFERENCES films (id) ON DELETE CASCADE,
    genre_id int REFERENCES genres (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    id int generated by default as identity primary key,
    email varchar(100) NOT NULL,
    login varchar(100) NOT NULL,
    name varchar(100),
    birthday date
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id int REFERENCES films (id) ON DELETE CASCADE,
    user_id int REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id int REFERENCES users (id) ON DELETE CASCADE,
    friend_id int REFERENCES users (id) ON DELETE CASCADE,
    status boolean,
    PRIMARY KEY (user_id, friend_id)
);